### ISSUE TITLE
Can you update the MongoDB version from 2.4.10?

### ISSUE THREAD

**Issue by SeppPenner** [GabrielRF/Docker-MongoDB-RPi#4]
The latest version of MongoDB is [4.0](https://docs.mongodb.com/manual/). Can you update the Dockerfile to install Version 4.0 instead of 2.4.10?

**Comment by GabrielRF** [comment]
It should download the last available version for RPi..
https://github.com/GabrielRF/Docker-MongoDB-RPi/blob/00b2e854387dfdbf123d565505d67e574abecca0/Dockerfile#L7 

2.4.0 is the one available for RPi, unfortunately..

**Comment by SeppPenner** [comment]
@GabrielRF Sure that's the latest version for the Raspberry Pi. However, I do not want to use a legacy version of MongoDB. Do you probably know how to install it from binaries?

**Comment by GabrielRF** [comment]
@SeppPenner, 3.2 I know is possible. Never heard of a 4.0 on RPi.. 
I've tried this once..
https://andyfelong.com/2018/03/mongodb-3-2-64-bit-running-on-raspberry-pi-3-with-caveats/
It works, but it's __not official__..

**Comment by SeppPenner** [comment]
Hi @GabrielRF. Thank you for the information. I will try this and check if it works for me.
